sonar.projectKey=go-project
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
# sonar.host.url=http://localhost:9000
# sonar.token=sqp_451a11c69014dc2281e36c3204881df2e56be8c0
sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out